### ISSUE TITLE
Inconsistencies in README 3

### ISSUE THREAD

**Issue by TriplEight** [koii-network/docs#10]
koii docs points to https://gitlab.com/koii-network/koii-docs
![image](https://github.com/koii-network/docs/assets/17856421/00727579-0084-4fea-b53f-5c15a499d188)

which doesn't exist
![image](https://github.com/koii-network/docs/assets/17856421/448695cd-f47b-408e-8298-09e37dc88287)

should it point to https://docs.koii.network/ instead?

**Comment by labrocadabro** [comment]
fixed
