### ISSUE TITLE
Inconsistencies in README

### ISSUE THREAD

**Issue by TriplEight** [koii-network/docs#8]
Top right in https://github.com/koii-network/docs:
  About [docs-koif.vercel.app](https://docs-koif.vercel.app/)
  ![image](https://github.com/koii-network/docs/assets/17856421/77bfae4a-7884-4ec1-bf9c-f477389c598d)

**Comment by hiroyukikumazawa** [comment]
also [docs-koif.vercel.app](https://docs-koif.vercel.app/) is broken url.

**Comment by labrocadabro** [comment]
fixed
